Feature/day 3
ayushpandey-successive/JS_Training pull request #3
Opened 2024-03-06 08:57 UTC by ayushpandey-successive

2024-03-13 11:02 UTC, saurabh-yadav-successive requested changes

2024-03-13 11:02 UTC, saurabh-yadav-successive commented on day-3/ques-1.js
> +const calc=(a,b,op)=>{
variable name should be meaningful.

2024-03-13 11:02 UTC, saurabh-yadav-successive commented on day-3/ques-1.js
> +    if(op=="+")
use switch case instead od if else condition

2024-03-13 11:02 UTC, saurabh-yadav-successive commented on day-3/ques-2.js
> +let range=4;
remove unnecessary let

2024-03-13 11:02 UTC, saurabh-yadav-successive commented on day-3/ques-2.js
> +for(let i = 0; i <range;i++)
correct the code format

2024-03-13 11:02 UTC, saurabh-yadav-successive commented on day-3/ques-2.js
> +        x=x+(z)+" ";
remove unnecessary brackets. and comments

2024-03-13 11:02 UTC, saurabh-yadav-successive commented on day-3/ques-2.js
> +console.log();
remove unnecessary logs

2024-03-13 11:02 UTC, saurabh-yadav-successive commented on day-3/ques-2.js
> +// 7 8 9 10
create it just like a function which takes input as a range and starting value.
After that IT creates pyramid accordingly.

2024-03-13 11:02 UTC, saurabh-yadav-successive commented on day-3/ques-2.js
> +
make it function which take r value and create pyramid accordingly.

2024-03-13 11:02 UTC, saurabh-yadav-successive commented on day-3/ques-2.js
> +let r=4;
remove unnecessary let, commented code and logs

2024-03-13 11:02 UTC, saurabh-yadav-successive commented on day-3/ques-2.js
> +for(let i = 1; i <r+1;i++)
code format

2024-03-13 11:02 UTC, saurabh-yadav-successive commented on day-3/ques-2.js
> +let m=5;
follow above comments

2024-03-14 04:29 UTC, ayushpandey-successive commented on day-3/ques-1.js
> +const calc=(a,b,op)=>{
resolved

2024-03-14 04:29 UTC, ayushpandey-successive commented on day-3/ques-1.js
> +    if(op=="+")
resolved

2024-03-14 04:29 UTC, ayushpandey-successive commented on day-3/ques-2.js
> +let range=4;
resolved

2024-03-14 04:29 UTC, ayushpandey-successive commented on day-3/ques-2.js
> +for(let i = 0; i <range;i++)
resolved

2024-03-14 04:29 UTC, ayushpandey-successive commented on day-3/ques-2.js
> +        x=x+(z)+" ";
resolved

2024-03-14 04:29 UTC, ayushpandey-successive commented on day-3/ques-2.js
> +console.log();
resolved

2024-03-14 04:29 UTC, ayushpandey-successive commented on day-3/ques-2.js
> +// 7 8 9 10
resolved

2024-03-14 04:30 UTC, ayushpandey-successive commented on day-3/ques-2.js
> +
resolved

2024-03-14 04:30 UTC, ayushpandey-successive commented on day-3/ques-2.js
> +let r=4;
resolved

2024-03-14 04:30 UTC, ayushpandey-successive commented on day-3/ques-2.js
> +for(let i = 1; i <r+1;i++)
resolved

2024-03-14 04:30 UTC, ayushpandey-successive commented on day-3/ques-2.js
> +let m=5;
resolved

2024-03-15 10:55 UTC, saurabh-yadav-successive approved these changes

2024-03-15 10:55 UTC, merged